version: '3.8'

services:
  flight-api:
    build: .
    image: flight-api:latest
    container_name: flight-api
    ports:
      - "8001:8001"
#    depends_on:
#      - mongodb
#      - redis
    environment:
      - SERVER_PORT=8001
#      - SERVER_ADDRESS=0.0.0.0
      - LOG_ACTIVE=dev
      - MONGO_DATABASE_URL=mongodb://admin_user:flight20241qazxsw21t@47.109.24.42:27017/flightsystem
      - REDIS_HOST=8.137.95.47
#      - REDIS_HOST=127.0.0.1
      - REDIS_PASSWORD=123456
      - CORS_ALLOWED_ORIGIN_PATTERNS=http://47.109.24.42,http://47.109.24.42:8001,http://47.109.24.42:8011,http://47.109.24.42/api,http://47.109.24.42:8001/api,http://47.109.24.42:8011/api,http://localhost:8011/api,http://localhost:8011

      #      - CORS_ALLOWED_ORIGIN_PATTERNS=http://47.109.24.42:*,http://localhost:*,*://*:80,*://*:8011
      - CORS_ALLOWED_CREDENTIALS=true
    volumes:
      - /var/log/docker/flight-api:/var/lib/docker/containers  # 挂载日志目录
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - flight-network

  mongodb:
    image: mongo:6.0
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin_user
      MONGO_INITDB_ROOT_PASSWORD: 123456
    volumes:
      - D:/docker/data/mongodb_data:/data/db  # 数据持久化
      - D:/docker/data/mongodb_conf/mongod.conf:/etc/mongo   # 配置文件
    networks:
      - flight-network

  redis:
    image: redis:6.2.6
    container_name: redis
    ports:
      - "6379:6379"
    command: redis-server --requirepass 123456
    volumes:
      - redis_data:/data
    networks:
      - flight-network

networks:
  flight-network:
    driver: bridge

volumes:
  mongodb_data:
  redis_data:
